-- 코드를 입력하세요
SELECT YEAR(OS.SALES_DATE) AS YEAR,
       MONTH(OS.SALES_DATE) AS MONTH,
       UI.GENDER,
       COUNT(DISTINCT UI.USER_ID) AS USERS
FROM USER_INFO UI INNER JOIN ONLINE_SALE OS ON UI.USER_ID=OS.USER_ID
WHERE UI.GENDER IS NOT NULL
GROUP BY 1, 2, 3
ORDER BY 1, 2, 3