-- 코드를 입력하세요
SELECT FP.PRODUCT_ID,
       FP.PRODUCT_NAME,
       SUM(FP.PRICE*FO.AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER FO INNER JOIN FOOD_PRODUCT FP ON FO.PRODUCT_ID=FP.PRODUCT_ID
WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5
GROUP BY 1
ORDER BY 3 DESC, 1